### ISSUE TITLE
UTF-8 versus bytes

### ISSUE THREAD

**Issue by Stebalien** [polydawn/refmt#8]
In go, `string` is just an immutable version of `[]byte`. Unfortunately, CBOR (and possibly JSON?) expect strings to be UTF-8 encoded unicode.

So, the immediate issue here is that one can end up producing non-utf8 strings in CBOR objects. Would it be possible to check on encode and either fall back on a byte array (preferable) or error out?

**Comment by heavenlyhash** [comment]
I think the most cost-effective place to armor against that is probably somewhere else.

It's true that the `string` type carrying UTF8 bytes isn't *enforced*.  However, I'd say it's definitely *canonical*, and it's fair to default to putting the burden of "don't make nonsensical strings" on the allocator of the string.

Mostly because *verifying it* is also *not free*: What if several different libraries all individually decide to implement MAX_PARANOIA at their boundaries, unknowing that all the others in the program have also done so?  The result is a huge waste of CPU time -- There's no way for a UTF8 validity check to be anything better than linear-time cost on size of the string, and that adds up fast.

So, just like any other input validation, you probably only want to do it once, and only if you have to -- as a rule of thumb, an efficient program design should be picking the boundary for validation, doing the work precisely once at that boundary, and then respecting its own invariants.  And in our specific case as a serializer, half the time the input strings are coming from constants in the program itself, which are most definitely UTF8 -- rechecking that compile-time static guarantee would be the epitome of waste!

Summary: I'm not dead-set against it, but a case has to be made for where it's reasonable and efficient systemically, because I *am* pretty against an swamp of `O(l)*O(n_strings)` overhead by default.  And in particular, I think checking UTF8 normalization on the way *out* is kinda backwards; that means some *other* parts of the program are already throwing around Distinctly Weird string values, and it's probably a symptom of latent bugs in more than one place.

**Comment by Stebalien** [comment]
My primary concern is that I'm trying to write a library on top of refmt and I'd like to catch errors as early as possible (I don't control my users' data). Unfortunately, use of strings for binary data is fairly common in go because they're immutable and can be used as keys. In our case, serialization *is*, effectively, the the application boundary (it's where we accept data and store it).

> There's no way for a UTF8 validity check to be anything better than linear-time cost on size of the string, and that adds up fast.

Technically, serialization is linear in the length of the data but I guess the constant does matter in this case (one operation per n bytes versus n operations per byte).

---

After thinking about this, I believe we can just write adapters where necessary; this is where streaming parsers/serializers really shine. This option should be significantly more flexible anyways. Having an `EnforceCanonical` option for cbor decoders/encoders would be nice but isn't strictly necessary.

**Comment by heavenlyhash** [comment]
Okay, so after I a little more thought on this... I do agree you've got a point and this is definitely sometimes a desired feature.

- By my own logic about "validation on boundaries": well, {de,}serialization probably is that boundary...!
- It *is* probably sensible to do this validation in the {de,}serializer parts (or, possibly implemented as something more pluggable that works on the `Token`-stream level), where we've already got strings in hand individually.  Writing another reflective traverser to check this would be possible (...actually, if we did it on `Token` streams, you could plug it into a obj.Marshaller/obj.Unmarshaller pair, easy), but reflection is a lot of cpu time to spend twice without a good reason.

Also still:

- I think this feature should probably be implemented on *de*serialization first, and that's the more sensible one to enable.  Enabling canonicalization checks on serialization should be more like a paranoia mode.
- Yep, definitely optional and controlled by flags.

I don't know if I'll have time to attack this anytime soon.  I'm talked into it though; PRs would be welcome :)
